// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessLogic.Models.GuestGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ArrivalOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ArrivalOrder"));

                    b.Property<DateTimeOffset>("ArrivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SeatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("ArrivalOrder")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ArrivalOrder"));

                    b.HasIndex("Status", "ArrivalOrder");

                    b.HasIndex("TableId", "Status");

                    b.ToTable("GuestGroups", null, t =>
                        {
                            t.HasCheckConstraint("CK_GuestGroups_Size", "[Size] BETWEEN 1 AND 6");

                            t.HasCheckConstraint("CK_GuestGroups_State", "([Status] = 'Waiting' AND [TableId] IS NULL AND [SeatedAt] IS NULL AND [LeftAt] IS NULL) OR\n([Status] = 'Seated' AND [TableId] IS NOT NULL AND [SeatedAt] IS NOT NULL AND [LeftAt] IS NULL) OR\n([Status] = 'Completed' AND [TableId] IS NOT NULL AND [SeatedAt] IS NOT NULL AND [LeftAt] IS NOT NULL) OR\n([Status] = 'Left' AND [TableId] IS NULL AND [SeatedAt] IS NULL AND [LeftAt] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BusinessLogic.Models.RestaurantTable", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RestaurantTables", null, t =>
                        {
                            t.HasCheckConstraint("CK_RestaurantTables_Capacity", "[Capacity] BETWEEN 2 AND 6");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 3
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 5
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 6
                        });
                });

            modelBuilder.Entity("BusinessLogic.Models.GuestGroup", b =>
                {
                    b.HasOne("BusinessLogic.Models.RestaurantTable", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
